// RAD HATS FOR RAD HUMANS — the collection
// Each hat: name, story (DRAFT, Svet to review), and placeholder style.
// PHOTO SWAP: drop a photo named photos/hat-01.jpg (02, 03 ... 50) into the
// photos/ folder and it automatically replaces that hat's placeholder.
// No code changes needed.

const HATS = [
  { name: "The First One", story: "The hat that started everything. I ordered a pretty cool hat on Etsy, then thought, wait, I could make this. Everyone got a little obsessed. Fifty hats later, here we are.", shape: "fedora", base: "#bf5b43", band: "#2b2724", accent: "#d9a441" },
  { name: "Franti", story: "Made for Michael Franti, who performed in it on stage. Watching one of my favorite musicians sing in a Rad Hat remains one of the radder moments of my life.", shape: "widebrim", base: "#2b2724", band: "#d9a441", accent: "#bf5b43" },
  { name: "Rad", story: "Made for the raddest soul I have ever known, my dog Rad. He wore it like he knew exactly how good he looked. He did.", shape: "bucket", base: "#d9a441", band: "#bf5b43", accent: "#2b2724" },
  { name: "Sausalito Sunday", story: "Born on a foggy Sunday by the bay, the kind of afternoon that changes your life if you let it.", shape: "boater", base: "#7a8c5e", band: "#f6efe6", accent: "#bf5b43" },
  { name: "The Karl", story: "Named after the store in Sausalito that first believed in Rad Hats, and after the fog that rolls over it every evening like clockwork.", shape: "fedora", base: "#5b6770", band: "#f6efe6", accent: "#d9a441" },
  { name: "Marin Morning", story: "Golden hills, cold coffee, warm light. This one belongs to slow mornings and big plans.", shape: "widebrim", base: "#c98a4b", band: "#7a8c5e", accent: "#2b2724" },
  { name: "The Tom & Jerry", story: "Named for the two teachers who taught me to focus on the moment and capture the story. Yes, really, Tom and Jerry.", shape: "boater", base: "#f6efe6", band: "#bf5b43", accent: "#2b2724" },
  { name: "Mental Wealth", story: "A reminder you can wear. Thirty percent of every Rad Hat went to mental health services, and this one carried that mission proudly.", shape: "fedora", base: "#0a8a93", band: "#f6efe6", accent: "#d9a441" },
  { name: "The Channing", story: "I adopted Rad after crying through the movie Dog. This hat is a thank you note to Channing Tatum, who has no idea he changed my life.", shape: "cowboy", base: "#8b6347", band: "#2b2724", accent: "#d9a441" },
  { name: "Tail Wag", story: "Made the week Rad walked up to me at the shelter and put his head on my knee. Some hats hold whole chapters.", shape: "bucket", base: "#bf5b43", band: "#f6efe6", accent: "#7a8c5e" },
  { name: "Studio Door", story: "The first hat finished in the Rad Hat Studio. The paint was still drying on the walls.", shape: "fedora", base: "#2b2724", band: "#bf5b43", accent: "#f6efe6" },
  { name: "Golden Hour", story: "Stitched entirely between five and seven in the evening, when the light in Marin turns everything honest.", shape: "widebrim", base: "#d9a441", band: "#2b2724", accent: "#bf5b43" },
  { name: "The Boutique Three", story: "Made to celebrate Rad Hats landing in its third boutique in under a year. I wore it for a week straight.", shape: "boater", base: "#bf5b43", band: "#d9a441", accent: "#2b2724" },
  { name: "Sea Salt", story: "For a sailor who wanted something the wind could not argue with. The wind lost.", shape: "bucket", base: "#5b8a9e", band: "#f6efe6", accent: "#2b2724" },
  { name: "The Optimist", story: "Commissioned by someone starting over. We built it brim first, the way you build a new life, foundation before flourish.", shape: "fedora", base: "#7a8c5e", band: "#d9a441", accent: "#f6efe6" },
  { name: "Angles Are Attitudes", story: "Named for the Sinatra line. Its owner wears it tilted exactly eleven degrees and will not be told otherwise.", shape: "fedora", base: "#2b2724", band: "#f6efe6", accent: "#bf5b43" },
  { name: "The Audrey", story: "Life is a party, dress like it. This one went to a woman who treats Tuesdays like premieres.", shape: "widebrim", base: "#f6efe6", band: "#2b2724", accent: "#d9a441" },
  { name: "Wildflower", story: "For a bride who got married barefoot on a hillside. The flowers on the band came from that hill.", shape: "widebrim", base: "#e8c8b8", band: "#7a8c5e", accent: "#bf5b43" },
  { name: "The Healer", story: "Made for a therapist who spends her days holding space for others. This hat holds space for her.", shape: "cloche", base: "#9e7b9b", band: "#f6efe6", accent: "#2b2724" },
  { name: "Big Sur or Bust", story: "Finished the night before a road trip down Highway 1. It came back with sand in the brim and a better story than mine.", shape: "cowboy", base: "#c98a4b", band: "#bf5b43", accent: "#2b2724" },
  { name: "The Poet", story: "For a writer who said she could not finish her book. She finished it. The hat takes partial credit.", shape: "cloche", base: "#2b2724", band: "#d9a441", accent: "#f6efe6" },
  { name: "Firekeeper", story: "Burnt orange, charcoal band, made for a man who hosts bonfires the way other people host dinner parties.", shape: "cowboy", base: "#b5601f", band: "#2b2724", accent: "#d9a441" },
  { name: "The Second Act", story: "Its owner left a thirty year career to open a bakery. The hat smells faintly of cinnamon now, and that is exactly right.", shape: "fedora", base: "#8b6347", band: "#f6efe6", accent: "#bf5b43" },
  { name: "Moonrise", story: "Deep indigo with a silver thread band. Made during a full moon, finished before it set.", shape: "widebrim", base: "#3b4a6b", band: "#c9c9d4", accent: "#f6efe6" },
  { name: "The Gardener", story: "Sage green and sun proof. Its owner talks to her tomatoes and they listen.", shape: "bucket", base: "#7a8c5e", band: "#d9a441", accent: "#f6efe6" },
  { name: "Pacific Standard", story: "For a surfer who measures time in tides. Worn at more sunrises than I have ever seen.", shape: "bucket", base: "#0a8a93", band: "#f6efe6", accent: "#bf5b43" },
  { name: "The Listener", story: "Made for a coach who taught me that listening is an art form. Quiet colors, loud presence.", shape: "cloche", base: "#5b6770", band: "#0a8a93", accent: "#f6efe6" },
  { name: "Confetti", story: "Commissioned for a fiftieth birthday by a woman who refuses to act her age. Correct decision.", shape: "boater", base: "#bf5b43", band: "#0a8a93", accent: "#d9a441" },
  { name: "The Sequoia", story: "For a park ranger. Built sturdy, weathered beautifully, like the trees she protects.", shape: "cowboy", base: "#6b4f3a", band: "#7a8c5e", accent: "#d9a441" },
  { name: "Honey", story: "For a beekeeper, naturally. Golden, calm, a little dangerous in the best way.", shape: "boater", base: "#d9a441", band: "#8b6347", accent: "#2b2724" },
  { name: "The Skeptic", story: "Its owner said he was not a hat person. He has worn it every day since. I rest my case.", shape: "fedora", base: "#5b6770", band: "#2b2724", accent: "#bf5b43" },
  { name: "Tattoo Money", story: "Made the same month I started practicing tattooing. One art form funding another, the way it has always worked for me.", shape: "fedora", base: "#2b2724", band: "#0a8a93", accent: "#f6efe6" },
  { name: "The Matriarch", story: "A gift from three siblings to their mother on her eightieth. She requested something with attitude. Delivered.", shape: "widebrim", base: "#9e7b9b", band: "#2b2724", accent: "#d9a441" },
  { name: "Foghorn", story: "Bold enough to be seen across the bay in full fog. Its owner is the same.", shape: "bucket", base: "#bf5b43", band: "#2b2724", accent: "#f6efe6" },
  { name: "The Dreamer", story: "Sky blue with a cream band. Made for someone who quit the practical plan, and is doing fine, thank you.", shape: "cloche", base: "#5b8a9e", band: "#f6efe6", accent: "#d9a441" },
  { name: "Saturday Market", story: "For a flower farmer who sells peonies at the Saturday market. The hat gets compliments. The peonies get jealous.", shape: "widebrim", base: "#f6efe6", band: "#7a8c5e", accent: "#bf5b43" },
  { name: "The Navigator", story: "For a pilot who flies small planes over the headlands. Built snug. The cockpit window stays closed anyway, but still.", shape: "fedora", base: "#3b4a6b", band: "#d9a441", accent: "#f6efe6" },
  { name: "Embers", story: "Rust, copper, and char. Made in autumn, obviously.", shape: "cowboy", base: "#b5601f", band: "#8b6347", accent: "#2b2724" },
  { name: "The Professor", story: "Tweedy and sharp, for a teacher who wanted his students to remember at least one thing about him. They remember the hat. He counts it.", shape: "fedora", base: "#8b7355", band: "#2b2724", accent: "#bf5b43" },
  { name: "Hummingbird", story: "Small, quick, impossibly bright. Its owner is five foot one and runs three companies.", shape: "cloche", base: "#0a8a93", band: "#bf5b43", accent: "#d9a441" },
  { name: "The Anniversary", story: "He bought hats for both of them, year ten. Hers is this one. His is hat number forty two. They wear them together and look ridiculous and perfect.", shape: "widebrim", base: "#e8c8b8", band: "#bf5b43", accent: "#2b2724" },
  { name: "The Other Anniversary", story: "See hat number forty one. This is his. He claims his is radder. The jury, me, remains diplomatically silent.", shape: "fedora", base: "#2b2724", band: "#e8c8b8", accent: "#bf5b43" },
  { name: "Lighthouse", story: "White with a charcoal band, for a writer who lives alone by the water and likes it that way.", shape: "boater", base: "#f6efe6", band: "#2b2724", accent: "#0a8a93" },
  { name: "The Comeback", story: "Made for someone one year sober. The inside band is embroidered with a date only she knows.", shape: "fedora", base: "#7a8c5e", band: "#f6efe6", accent: "#d9a441" },
  { name: "Mariposa", story: "For a dancer from Oaxaca who wanted home stitched into something she could wear. We got close.", shape: "widebrim", base: "#bf5b43", band: "#d9a441", accent: "#0a8a93" },
  { name: "The Early Bird", story: "Its owner swims in the bay at six every morning, all year. The hat waits on the dock. Smart hat.", shape: "bucket", base: "#5b8a9e", band: "#2b2724", accent: "#f6efe6" },
  { name: "Velvet Underground", story: "Black on black on black, for a musician who plays late sets in the city. It has seen things.", shape: "fedora", base: "#1d1a18", band: "#2b2724", accent: "#5b6770" },
  { name: "The Wink", story: "Rad came with his name before I ever met him, three months after I named the company. This hat is for winks from the universe.", shape: "boater", base: "#d9a441", band: "#0a8a93", accent: "#bf5b43" },
  { name: "Open Water", story: "For a marine biologist who spends more time on boats than land. Salt tested, science approved.", shape: "bucket", base: "#0a8a93", band: "#3b4a6b", accent: "#f6efe6" },
  { name: "Hat Number Fifty", story: "The fiftieth custom Rad Hat. I cried a little when it sold, then I started on fifty one. That is the whole secret, you just keep making the next one.", shape: "widebrim", base: "#bf5b43", band: "#d9a441", accent: "#f6efe6" }
];
